import type { Metadata } from "next";
import { ToastContainer } from "react-toastify";
import { Londrina_Solid } from "next/font/google";
import "./globals.css";
import "react-toastify/dist/ReactToastify.css";

const inter = Londrina_Solid({ weight: "400", subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-screen">
      <body className={`${inter.className} h-screen`}>
        {children}
        <ToastContainer />
      </body>
    </html>
  );
}
